development:
  adapter: solid_cable

test:
  adapter: solid_cable

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: map_the_maker_production
